#!/bin/bash

# Define some useful variables for printing
bold=`tput bold`
normal=`tput sgr0`

#add new repo to config file
if [[ $1 == "-add" ]] || [[ $1 == "-a" ]]; then
        if [[ ! -z $2 ]]; then 
                if [[ ! -f ~/.batchgitrc ]]; then
                        touch ~/.batchgitrc
                        echo -e "making ~/.batchgitrc file \n"
                fi
                if [[ $2 == "./" ]]; then
                        echo $(pwd) >> ~/.batchgitrc
                else
                        echo $2 >> ~/.batchgitrc
                        echo -e "Added $2 to the ~/.batchgitrc file"
                fi
                sort -u -o ~/.batchgitrc ~/.batchgitrc
        else
                echo "you need to add the directory after the flag!"
        fi
        choice=y
fi

#tests for config file, or runs if forced to redo config
if [[ $1 == "-f" ]] || [[ ! -f ~/.batchgitrc ]] || [[ $1 == "-find" ]]; then
        findgit=( $(find ~ -type d -name .git | xargs -n 1 dirname) )
        numfind=${#findgit[@]}
        echo -e "There are $numfind git repositories \n"

        if [[ ! -f ~/.batchgitrc ]]; then
                touch ~/.batchgitrc
                echo -e "making ~/.batchgitrc file \n"
        else
                mv ~/.batchgitrc ~/.batchgitrc.bak
                touch ~/.batchgitrc
                echo -e "making a new ~/.batchgitrc file and backing up old to ~/.batchgitrc.bak \n"
        fi

        for gdir in "${findgit[@]}"; do
                        echo -e "$gdir"
                        read -p "Would you like to watch this repository? (y/n): " -n 1 -r
                        if [[ $REPLY =~ ^[Yy]$ ]]; then
                                echo $gdir >> ~/.batchgitrc
                        fi
                        echo -e "\n"
        done
        choice=y
fi


#multiple choice for no option or post config
if [[ $# == 0 ]] || [[ $choice == "y" ]]; then
while true; do
        echo -e """
1) \t git status
2) \t git pull
3) \t git push
4) \t quit
        """
        read -p "What happens now? " whatnow
        case $whatnow in
                [1]* ) now=gstatus;break;;
                [2]* ) now=gpull;break;;
                [3]* ) now=gpush;break;;
                [4]* ) now=quit;break;;
                [quit]* ) now=quit;break;;
                [exit]* ) now=quit;break;;
        esac
done
fi

#quits script if option selected
if [[ $now == "quit" ]]; then
        printf "\n"
        exit
fi

#Array where paths are held
paths=( $(cat ~/.batchgitrc) )     

#Check to ensure all local directories still exist
let i=1
for dir in "${paths[@]}"; do
        let i+=1
        if [[ ! -d $dir ]]; then
                clean=$(echo $dir | sed 's/\///g')
                echo -e "The $dir directory doesn't exist anymore and has been removed from the config file"
                sed -e "s|$dir||g" -i  ~/.batchgitrc
        fi
done
sed -e '/^$/d' -i ~/.batchgitrc 
paths=( $(cat ~/.batchgitrc) )     

#spacing for neatness
printf "\n"

#git status
if [[ $1 == "-status" ]] || [[ $now == "gstatus" ]] || [[ $1 == "-s" ]]; then
        let i=1
        for dir in "${paths[@]}"; do
                let i+=1
                cd $dir
                REPO=${PWD##*/}
                echo ${bold}"Repository: $REPO ${normal}"
                untracked=$(git status | grep -A 3 'Untracked' | tail -n 1 | sed 's/^[ \t]*//g')
                modified=$(git status | grep 'modified:' | sed 's/modified://g' | sed 's/^[ \t]*//g')
                if [[ ! -z $untracked ]]; then
                        echo -e "Untracked: \n\e[1;31m$untracked\e[0m"
                fi
                if [[ ! -z $modified ]]; then
                        echo -e "Modified: \n\e[1;31m$modified\e[0m"
                fi
                echo
        done
printf "\n"
exit
fi

#git push
if [[ $1 == "-push" ]] || [[ $now == "gpush" ]] || [[ $1 == "-u" ]] || [[ $1 == "-n" ]]; then
	let i=1
	for dir in "${paths[@]}"; do
		let i+=1
		cd $dir
		pwd
		git pull
		git push
        printf "\n"
	done
printf "\n"
        if [[ $1 == "-n" ]]; then
                echo -e "\nAll done for the day!\n"
                        printf """
+      o     +              o   
    +             o     +       +
o          +
    o  +           +        +
+        o     o       +        o
-_-_-_-_-_-_-_,------,      o 
_-_-_-_-_-_-_-|   /\_/\  
-_-_-_-_-_-_-~|__( ^ .^)  +     +  
_-_-_-_-_-_-_-''  ''      
+      o         o   +       o
    +         +
o        o         o      o     +
    o           +
+      +     o        o      +    
\n"""
        fi
exit
fi

#git pull
if [[ $1 == "-pull" ]] || [[ $now == "gpull" ]] || [[ $1 == "-d" ]]; then
	let i=1
	for dir in "${paths[@]}"; do
		let i+=1
		cd $dir
		pwd
		git pull
        printf "\n"
	done
printf "\n"
exit
fi

#error message
echo "sorry, that command didn't work! Try again"
printf "\n"
exit
